Feature/recycler view
grigorevmp/MTS_Homework pull request #2
Opened 2021-07-16 09:09 UTC by grigorevmp

hw 4

2021-07-21 14:49 UTC, NikolayUkhvarov requested changes

2021-07-21 14:49 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/MovieInfoAdapter.kt
> +        const val VIEW_TYPE_ONE = 1
малоговорящие названия

2021-07-21 14:49 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/MovieInfoAdapter.kt
> +    private var moviesModel = MoviesModel(MoviesDataSourceImpl())
нужно сетить данные извне, зачем адаптеру знать источник данных?

2021-07-21 14:49 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/ViewHolder.kt
> +            when (movie.rateScore) {
придумай, как упростить до двух строчек

2021-07-21 14:49 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/ViewHolder.kt
> +        when (movie.rateScore) {
тут тоже

2021-07-22 13:08 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/ViewHolder.kt
> +            when (movie.rateScore) {
Упростил обернув в AppCompatRatingBar

2021-07-22 13:08 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/MovieInfoAdapter.kt
> +    private var moviesModel = MoviesModel(MoviesDataSourceImpl())
Да, оно так и сделано, это лишняя переменная, удалил

2021-08-04 15:55 UTC, NikolayUkhvarov approved these changes

2021-08-06 11:12 UTC, merged