Feature/fragments
grigorevmp/MTS_Homework pull request #3
Opened 2021-07-20 12:15 UTC by grigorevmp

2021-08-04 16:05 UTC, NikolayUkhvarov requested changes

2021-08-04 16:05 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesDetailFragment.kt
> +        when (arguments?.getInt("MovieRate")) {
это всё можно сделать короче, добавив вьюхи в лист и пройдясь for или foreachindexed

2021-08-06 11:40 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesDetailFragment.kt
> +        when (arguments?.getInt("MovieRate")) {
Ой, я поправил в другом месте, а тут забыл.
Исправлено

2021-08-06 16:04 UTC, NikolayUkhvarov approved these changes

2021-08-07 13:36 UTC, merged