Feature/coroutines
grigorevmp/MTS_Homework pull request #4
Opened 2021-07-25 14:58 UTC by grigorevmp

2021-08-06 16:08 UTC, NikolayUkhvarov requested changes

2021-08-06 16:08 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesFragment.kt
> +                    delay(2000)
перенеси в источник данных, тут только отображение

2021-08-07 15:44 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesFragment.kt
> +                    delay(2000)
Исправил

2021-08-09 12:27 UTC, NikolayUkhvarov approved these changes

2021-08-10 08:38 UTC, merged