Feature/mvvm
grigorevmp/MTS_Homework pull request #5
Opened 2021-08-06 11:35 UTC by grigorevmp

2021-08-06 16:10 UTC, NikolayUkhvarov requested changes

2021-08-06 16:10 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesDetailFragment.kt
> +            text = safeArgs.title
передавай в аргументах только id, остальное проси через вьюмодель у источника данных (можно без задержки)

2021-08-07 15:43 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesDetailFragment.kt
> +            text = safeArgs.title
Исправил

2021-08-09 12:33 UTC, NikolayUkhvarov requested changes

2021-08-09 12:33 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/mvvm/MvvmViewModel.kt
> +class MvvmViewModel : ViewModel() {
вьюмодель чего? нужно переименовать под что-то конкретное

2021-08-09 12:33 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/mvvm/MvvmViewModel.kt
> +class MvvmViewModel : ViewModel() {
лучше разделить вьюмодели для списка и карточки фильма

2021-08-10 10:48 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/mvvm/MvvmViewModel.kt
> +class MvvmViewModel : ViewModel() {
Сделано

2021-08-10 11:55 UTC, NikolayUkhvarov approved these changes

2021-08-10 11:58 UTC, merged