Feature/room
grigorevmp/MTS_Homework pull request #6
Opened 2021-08-08 12:43 UTC by grigorevmp

2021-08-18 13:15 UTC, NikolayUkhvarov requested changes

2021-08-18 13:15 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesFragment.kt
> +        CoroutineScope(Dispatchers.IO).launch {
почему корутина во вью?
репозитория тоже не должно быть

2021-08-18 13:15 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/ProfileFragment.kt
> +        CoroutineScope(Dispatchers.IO).launch {
без корутин во вью

2021-08-18 13:15 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/ProfileFragment.kt
> +            CoroutineScope(Dispatchers.IO).launch {
и тут

2021-08-18 13:15 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/movieData/MovieRepository.kt
> +class MovieRepository(context: Context) {
нужно придумать, как не передавать сюда контекст из вью

2021-08-18 13:15 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserDatabase.kt
> +abstract class UserDatabase : RoomDatabase() {
для чего две бд?

2021-08-21 10:28 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/MoviesFragment.kt
> +        CoroutineScope(Dispatchers.IO).launch {
Перенёс

2021-08-21 10:28 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/ProfileFragment.kt
> +        CoroutineScope(Dispatchers.IO).launch {
Убрал

2021-08-21 10:28 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/ProfileFragment.kt
> +            CoroutineScope(Dispatchers.IO).launch {
Убрал

2021-08-21 10:28 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/movieData/MovieRepository.kt
> +class MovieRepository(context: Context) {
Избавился

2021-08-21 10:30 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserDatabase.kt
> +abstract class UserDatabase : RoomDatabase() {
Не совсем понял, 2 бд?

2021-08-24 15:34 UTC, NikolayUkhvarov requested changes

2021-08-24 15:34 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserDatabase.kt
> +abstract class UserDatabase : RoomDatabase() {
ну отдельная для userdao

2021-08-24 15:34 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserModel.kt
> +class LoadUserTask(
так так так
у нас же корутины для асинхронного выполнения
асинктаски мертвы, не трогай их, пожалуйста

2021-08-26 08:24 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserModel.kt
> +class LoadUserTask(
Заменил всё корутинами

2021-08-26 08:25 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserDatabase.kt
> +abstract class UserDatabase : RoomDatabase() {
Ну я использовал паттерн с лекции для этого
Планировал сделать поддержку нескольких аккаунтов, поэтому бд, просто пока не допилено

2021-08-26 16:33 UTC, NikolayUkhvarov requested changes

2021-08-26 16:33 UTC, NikolayUkhvarov commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserModel.kt
> +class LoadUserTask(
сами функции, начинаю с loadUser стоит сделать suspend и вызывать их из корутин во вьюмодели или репозитории, тогда колбэки не нужны

наследовать твои "таски" от вьюмодели совсем неправильно

2021-08-26 19:17 UTC, grigorevmp commented on app/src/main/java/com/mikhailgrigorev/mts_home/userData/UserModel.kt
> +class LoadUserTask(
Как же сложно, когда в каждой статье разная реализация)
Так, если я правильно понял то вот так?

2021-08-31 21:12 UTC, NikolayUkhvarov approved these changes

2021-09-01 16:09 UTC, merged